// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2M0SNHvnIGfiYNMo-rK97EEOiagI2GuY',
    appId: '1:952287628874:web:41cba1657c87b42ebb20b3',
    messagingSenderId: '952287628874',
    projectId: 'pict-hacka',
    authDomain: 'pict-hacka.firebaseapp.com',
    storageBucket: 'pict-hacka.firebasestorage.app',
    measurementId: 'G-GZ062YZ5FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnaN6IdgpgM5KsrUoHdE-fVq2X1TG3l1s',
    appId: '1:952287628874:android:228b04ca43028071bb20b3',
    messagingSenderId: '952287628874',
    projectId: 'pict-hacka',
    storageBucket: 'pict-hacka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_sjPuClA9oA30zrQ6fYZQQAOArjOjgSQ',
    appId: '1:952287628874:ios:ce8e14871afa7592bb20b3',
    messagingSenderId: '952287628874',
    projectId: 'pict-hacka',
    storageBucket: 'pict-hacka.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_sjPuClA9oA30zrQ6fYZQQAOArjOjgSQ',
    appId: '1:952287628874:ios:ce8e14871afa7592bb20b3',
    messagingSenderId: '952287628874',
    projectId: 'pict-hacka',
    storageBucket: 'pict-hacka.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2M0SNHvnIGfiYNMo-rK97EEOiagI2GuY',
    appId: '1:952287628874:web:53b4a4bca818a31abb20b3',
    messagingSenderId: '952287628874',
    projectId: 'pict-hacka',
    authDomain: 'pict-hacka.firebaseapp.com',
    storageBucket: 'pict-hacka.firebasestorage.app',
    measurementId: 'G-NRKCNSFTGV',
  );
}
